openapi: 3.0.2
info:
  contact:
    url: https://github.com/moov-io/customers
  description: |
    Customers focuses on solving authentic identification of humans who are legally able to hold and transfer currency within the US. Primarily this project solves [Know Your Customer](https://en.wikipedia.org/wiki/Know_your_customer) (KYC), [Customer Identification Program](https://en.wikipedia.org/wiki/Customer_Identification_Program) (CIP), [Office of Foreign Asset Control](https://www.treasury.gov/about/organizational-structure/offices/Pages/Office-of-Foreign-Assets-Control.aspx) (OFAC) checks and verification workflows to comply with US federal law and ensure authentic transfers. Also, Customers has an objective to be a service for detailed due diligence on individuals and companies for Financial Institutions and services in a modernized and extensible way.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: Customers Admin API
  version: v1
servers:
- description: Local development
  url: http://localhost:9097
tags:
- description: Customers endpoints which are only meant to be exposed for admin dashboards
    and operations.
  name: Admin
- description: Endpoints for searching, creating, and verifying individuals according
    to US government criteria for money movement within the country.
  name: Customers
paths:
  /live:
    get:
      description: Get the status of each depdendency
      operationId: getLivenessProbes
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LivenessProbes'
          description: The status of dependencies
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LivenessProbes'
          description: An error occurred when checking dependencies
      summary: Get Liveness Probes
      tags:
      - Admin
  /version:
    get:
      description: Show the current version of Customers
      operationId: getVersion
      responses:
        "200":
          content:
            text/plain:
              schema:
                example: v0.4.0
                type: string
          description: The current version running
      summary: Get Version
      tags:
      - Admin
  /customers/{customerID}/disclaimers:
    post:
      description: Create a disclaimer for the specified customerID to approve
      operationId: createCustomerDisclaimer
      parameters:
      - description: Customer ID
        explode: false
        in: path
        name: customerID
        required: true
        schema:
          example: e210a9d6-d755-4455-9bd2-9577ea7e1081
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateUserDisclaimer'
        required: true
      responses:
        "200":
          description: Created disclaimer
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: See error message
      summary: Create disclaimer
      tags:
      - Customers
components:
  schemas:
    LivenessProbes:
      example:
        watchman: good
      properties:
        watchman:
          description: Either an error from checking Customers or good as a string.
          example: good
          type: string
    CreateUserDisclaimer:
      example:
        documentId: ad3cb5fe
        text: Please read and accept the attached document
      properties:
        documentId:
          description: Optional ID for document to display alongside
          example: ad3cb5fe
          type: string
        text:
          description: Free form text agreement or policy to display
          example: Please read and accept the attached document
          type: string
      required:
      - text
    Error:
      properties:
        error:
          description: An error message describing the problem intended for humans.
          example: Validation error(s) present.
          type: string
      required:
      - error
